version: 2.1

workflows:
  version: 2
  release:
    jobs:
      - announce
      - hold:
          type: approval
          requires:
            - announce
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - hold
          filters:
            branches:
              ignore:
                - master

jobs:
  announce:
    docker:
      - image: circleci/golang:1.13
    steps:
      - run: echo "Placeholder"
  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          CGO_ENABLED: 0
          GOBIN: /tmp

    steps:
      - checkout
      - run:
          name: 
          command: |
            git config --global user.email "ryanhaley@frazer.biz"
            git config --global user.name "Ryan Haley"
      - run: git checkout master
      - run: git pull origin master
      - run: git reset --hard origin/master
      - run: git log --oneline | head -n10
      - run: echo ${CIRCLE_BRANCH}
      - run:
          name: Merge into master
          command: |
            git merge ${CIRCLE_BRANCH}
      - run:
          name: Install changelog utility
          command: go install .
      - run:
          name: Update version and CHANGELOG
          command: ${GOBIN}/changelog
      - run:
          name: Push to master
          command: |
            git push origin master
            git push --tags