version: 2.1

workflows:
  version: 2
  release:
    branches:
      ignore:
        - master
    jobs:
      - hold:
          type: approval
      - release:
          requires:
            - hold

jobs:
  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          CGO_ENABLED: 0
          GOBIN: /tmp

    steps:
      - checkout
      - run:
          name: 
          command: |
            git config --global user.email "ryanhaley@frazer.biz"
            git config --global user.name "Ryan Haley"
      - run:
          name: Merge into master
          command: |
            git checkout master
            git merge ${CIRCLE_BRANCH}
      - run:
          name: Install changelog utility
          command: go install .
      - run:
          name: Update version and CHANGELOG
          command: ${GOBIN}/changelog
      - run:
          name: Push to master
          command: |
            git push origin master
            git push --tags