version: 2.1

workflows:
  version: 2
  release:
    jobs:
      - release

jobs:
  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          CGO_ENABLED: 0
          GOBIN: /tmp

    steps:
      - checkout
      - run: git checkout master
      - run: git merge ${CIRCLE_BRANCH}
      - run: go install .
      - run: ${GOBIN}/changelog
      - run: git tag
      - run: git log